server:
  port: 7001

eureka:
  instance:
    hostname: localhost       # eureka服务端的实例名称
  client:
    register-with-eureka: false # false表示7001不向注册中心注册自己
    fetch-registry: false       # false表示不需要检索微服务，因为自己就是注册中心，职责是维护服务实例
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/  # 设置与Eureka Server交互的地址，注册服务和查询服务都需要依赖这个地址
